site_name: Obecní kronika Stará Ves
site_description: Historická kronika obce 1923-1991
theme:
  name: material
  language: cs
  features:
  - navigation.instant
  - navigation.collapse
  - navigation.prune
  - navigation.indexes
  - search.highlight
  - navigation.top
  - search.highlight
  - search.share
plugins:
- search:
    lang: en
- meta
markdown_extensions:
- meta
- toc:
    permalink: true
- admonition
- pymdownx.details
- pymdownx.superfences
nav:
- Úvod: index.md
- KRONIKA STARÁ VES: chapter_001.md
- 1923–1953, 1979–1991: chapter_002.md
- Obec Stará Ves: chapter_003.md
- Z minulostí obce:
  - Z minulostí obce: chapter_004.md
  - Vrchnost do r. 1620: chapter_005.md
  - Regista: chapter_006.md
  - Historie Hradu Navarova: chapter_007.md
  - Doba od r. 1620 do r. 1634: chapter_008.md
  - Doba od r. 1634: chapter_009.md
  - Protireformace od r. 1648: chapter_010.md
  - Památnosti: chapter_011.md
  - Od roku 1700: chapter_012.md
  - Od roku 1800: chapter_013.md
  - Sedláci v Staré Vsi r. 1842: chapter_014.md
  - Roku 1912: chapter_015.md
  - Válka světová: chapter_016.md
  - Z roku 1915: chapter_017.md
  - R. 1917: chapter_018.md
  - R. 1918: chapter_019.md
- Dne 28. října byla prohlášena Československá republika:
  - Dne 28. října byla prohlášena Československá republika: chapter_020.md
  - R. 1919: chapter_021.md
  - R. 1920: chapter_022.md
  - R. 1921: chapter_023.md
  - Oběti Války ze Staré Vsi r. 1914 – 1918: chapter_024.md
  - Legionáři ze Staré Vsi: chapter_025.md
  - Rok 1922: chapter_026.md
  - Rok 1923: chapter_027.md
  - Patricijská jména z okolí: chapter_028.md
  - Regista: chapter_029.md
  - Z dějin městečka Vysokého: chapter_030.md
  - Rok 1923 (pokračování): chapter_031.md
  - 1923 (pokračování): chapter_032.md
  - Z Dějin národa českého: chapter_033.md
  - Rok 1924: chapter_034.md
  - Některá památnější úmrtí od roku 1881: chapter_035.md
  - Různé: chapter_036.md
  - Rok 1924: chapter_037.md
  - Památka: chapter_038.md
  - '1925': chapter_039.md
  - '1926': chapter_040.md
  - Rok 1927: chapter_041.md
  - '1928': chapter_042.md
  - '1929': chapter_043.md
  - '1930': chapter_044.md
  - '1931': chapter_045.md
  - '1932': chapter_046.md
  - '1933': chapter_047.md
  - '1934': chapter_048.md
- Dějiny školy staroveské: chapter_049.md
- Dějiny čísel starovesských:
  - Dějiny čísel starovesských: chapter_050.md
  - Č 1: chapter_051.md
  - Č. 2 U Holánku: chapter_052.md
  - Č. 3 U Syrovátku: chapter_053.md
  - Č. 4 U Hýrku: chapter_054.md
  - Č. 5 U Roztomilejch: chapter_055.md
  - Č.7 U Chalupenských: chapter_056.md
  - Č. 6 U Klikorku: chapter_057.md
  - Č. 8 V Janoušově chalupě: chapter_058.md
  - Č. 9 U Hajnů: chapter_059.md
  - Č. 10 U Staru.: chapter_060.md
  - Č. 11 Na Krumpešti: chapter_061.md
  - Č. 12 Na Pustině: chapter_062.md
  - Č. 13 U Pátku: chapter_063.md
  - Č. 14 U Ducháčku: chapter_064.md
  - Č. 15 U Přidanu: chapter_065.md
  - Č. 16 U Javůrku: chapter_066.md
  - Č. 17 U Koucku: chapter_067.md
  - Č. 18. U Petrušku: chapter_068.md
  - Č. 19 U Berku: chapter_069.md
  - Č. 20. U Vršťalu: chapter_070.md
  - Č. 21 U Housičku: chapter_071.md
  - Č. 22 U Čermáku: chapter_072.md
  - Č. 23 U Boudalováku: chapter_073.md
  - Č. 24 Na Kosnici: chapter_074.md
  - Č. 25 V Pazderně: chapter_075.md
  - Č. 26 V dolením Krčovi: chapter_076.md
  - Č. 27 Na Prutě: chapter_077.md
  - Č. 27 V Hořením Krčoví: chapter_078.md
  - Č. 28 U Končalu: chapter_079.md
  - Č. 29 V Potocích: chapter_080.md
  - Č. 30 U Zámečniku: chapter_081.md
  - Č. 31 U Blažku: chapter_082.md
  - Č. 32 U Duštů: chapter_083.md
  - Č. 33 U Nováku: chapter_084.md
  - Č. 34 U Vitošů: chapter_085.md
  - Č. 35 U Marků: chapter_086.md
  - Č. 36 U Petrů: chapter_087.md
  - Č. 37 U Peloušů: chapter_088.md
  - Č. 38 Na Podrybníku: chapter_089.md
  - Č. 53 U Woceďalku: chapter_090.md
  - Č. 39 U Smětalů: chapter_091.md
  - Č. 40 V dolením Mlýně: chapter_092.md
  - Č. 40 V Hořením Mlýně: chapter_093.md
  - Č. 42 U Starých Smětalu: chapter_094.md
  - Č. 43 U Zadních Vojáku: chapter_095.md
  - Č. 44 U Březáku: chapter_096.md
  - Č. 45 U Hořeních Vojáku: chapter_097.md
  - Č. 46 U Předních Vojáku: chapter_098.md
  - Č. 47 U Kucheláku: chapter_099.md
  - Č. 48 U Vlášku: chapter_100.md
  - Č. 49 Ve Staré Škole: chapter_101.md
  - Č. 50 U Procházku: chapter_102.md
  - Č. 51 U Klepaču: chapter_103.md
  - Č. 52 U Adámku: chapter_104.md
  - Č. 53 U Voceďálku: chapter_105.md
  - Č. 54 Na Skále: chapter_106.md
  - Č. 55 U Prutských: chapter_107.md
  - Č. 56 U Lukšu: chapter_108.md
  - Č. 57 U Holinku: chapter_109.md
  - Rod Čermákův: chapter_110.md
  - Rod Hevákův: chapter_111.md
  - Rod Hladíkův: chapter_112.md
- Rok 1935 – 1991:
  - Rok 1935 – 1991: chapter_113.md
  - '1935': chapter_114.md
  - '1936': chapter_115.md
  - '1937': chapter_116.md
  - '1938': chapter_117.md
  - '1939': chapter_118.md
  - '1940': chapter_119.md
  - '1941': chapter_120.md
  - '1942': chapter_121.md
  - '1943': chapter_122.md
  - '1944': chapter_123.md
  - Rok 1945: chapter_124.md
  - '1946': chapter_125.md
  - '1947': chapter_126.md
  - '1948': chapter_127.md
  - '1949': chapter_128.md
  - '1950': chapter_129.md
  - Rok 1951: chapter_130.md
  - '1952': chapter_131.md
  - '1953': chapter_132.md
  - Rok 1979: chapter_133.md
  - Rok 1980: chapter_134.md
  - Rok 1981: chapter_135.md
  - Dodatky k roku 1981: chapter_136.md
  - Rok 1982: chapter_137.md
  - Rok 1983: chapter_138.md
  - Rok 1984: chapter_139.md
  - Rok 1985: chapter_140.md
  - Rok 1986: chapter_141.md
  - Rok 1987: chapter_142.md
  - Rok 1988: chapter_143.md
  - Rok 1989: chapter_144.md
  - Rok 1990: chapter_145.md
  - Rok 1991: chapter_146.md
- Obsah: chapter_147.md
