site_name: Obecní kronika Stará Ves
site_description: Historická kronika obce 1923-1991
site_url: https://adbo28.github.io/kronika/
theme:
  name: material
  language: cs
  features:
  - navigation.instant
  - navigation.collapse
  - navigation.prune
  - navigation.indexes
  - search.highlight
  - navigation.top
  - search.highlight
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.6.2/fuse.min.js
plugins:
- search:
    lang: en
- meta
markdown_extensions:
- meta
- toc:
    permalink: true
    toc_depth: 0
- admonition
- pymdownx.details
- pymdownx.superfences
nav:
- Úvod: index.md
- KRONIKA STARÁ VES: chapters/chapter_001.md
- Základní informace o obci:
  - Základní informace o obci: chapters/chapter_002.md
  - Obec Stará Ves: chapters/chapter_003.md
  - Památnosti a významná místa: chapters/chapter_004.md
- Rané dějiny (do 1700):
  - Rané dějiny (do 1700): chapters/chapter_005.md
  - Vrchnost do roku 1620: chapters/chapter_006.md
  - Historie Hradu Navarova: chapters/chapter_007.md
  - Doba od r. <a id="1620-806bea">1620</a> do r. 1634: chapters/chapter_008.md
  - Doba od roku 1634: chapters/chapter_009.md
  - Protireformace od roku 1648: chapters/chapter_010.md
- 18. a 19. století (1700–1914):
  - 18. a 19. století (1700–1914): chapters/chapter_011.md
  - Od roku 1700: chapters/chapter_012.md
  - Od roku 1800: chapters/chapter_013.md
  - Sedláci v Staré Vsi roku 1842: chapters/chapter_014.md
  - Roku 1912: chapters/chapter_015.md
  - Některá památnější úmrtí od roku 1881: chapters/chapter_016.md
- První světová válka (1914–1918):
  - První světová válka (1914–1918): chapters/chapter_017.md
  - Válka světová: chapters/chapter_018.md
  - Průběh války (1915–1918): chapters/chapter_019.md
  - Oběti <a id="válka-bfccd5">Války</a> ze Staré Vsi r. <a id="1914-07a4e2">1914</a> – 1918: chapters/chapter_020.md
  - Legionáři ze Staré Vsi: chapters/chapter_021.md
- Meziválečné období (1918–1938):
  - Meziválečné období (1918–1938): chapters/chapter_022.md
  - Vznik Československé republiky (1918–1922): chapters/chapter_023.md
  - Roky 1923–1927: chapters/chapter_024.md
  - Roky 1928–1934: chapters/chapter_025.md
- Válečné a poválečné období (1935–1953):
  - Válečné a poválečné období (1935–1953): chapters/chapter_026.md
  - Předválečné roky (1935–1938): chapters/chapter_027.md
  - Druhá světová válka (1939–1945): chapters/chapter_028.md
  - Poválečné roky (1946–1953): chapters/chapter_029.md
- Novější dějiny (1979–1991):
  - Novější dějiny (1979–1991): chapters/chapter_030.md
  - Osmdesátá léta (1979–1989): chapters/chapter_031.md
  - Sametová revoluce a její následky (1989–1991): chapters/chapter_032.md
- Dějiny školy staroveské: chapters/chapter_033.md
- Historie domů a jejich obyvatel:
  - Historie domů a jejich obyvatel: chapters/chapter_034.md
  - Domy č. 1–20: chapters/chapter_035.md
  - Domy č. 21–40: chapters/chapter_036.md
  - Domy č. 41–57: chapters/chapter_037.md
  - Rody a genealogie: chapters/chapter_038.md
- Okolní obce a regiony:
  - Okolní obce a regiony: chapters/chapter_039.md
  - Z dějin městečka Vysokého: chapters/chapter_040.md
  - Patricijská jména z okolí: chapters/chapter_041.md
  - Z Dějin národa českého: chapters/chapter_042.md
- Přílohy:
  - Přílohy: chapters/chapter_043.md
  - Regista: chapters/chapter_044.md
  - Různé: chapters/chapter_045.md
- Ediční poznámka: chapters/chapter_046.md
- Indexy:
  - Čísla popisná: indexes/address_number.md
  - Klíčová slova: indexes/event.md
  - Jména: indexes/name.md
  - Roky: indexes/year.md
