site_name: Obecní kronika Stará Ves
site_description: Historická kronika obce 1923-1991
theme:
  name: material
  language: cs
  features:
  - navigation.instant
  - navigation.collapse
  - navigation.prune
  - navigation.indexes
  - search.highlight
  - navigation.top
  - search.highlight
  - search.share
  - toc.integrate
plugins:
- search:
    lang: en
- meta
markdown_extensions:
- meta
- toc:
    permalink: true
- admonition
- pymdownx.details
- pymdownx.superfences
nav: []
